config/routes.rb
Hospital::Application.routes.draw do
  resources :employees  do
    resources :professions
  end

  resources :professions

  get "home/index"

   root :to => 'home#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :contact, :cpf, :name

  has_many :professions
end

app/models/profession.rb
class Profession < ActiveRecord::Base
  belongs_to :employee
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController

  def index
    @professions = Profession.all
    respond_to do |format|
      format.html
      format.json {render json: @professions}
    end
  end

  def show
    @profession = Profession.find(params[:id])
    respond_to do  |format|
      format.html
      format.json {render json: @profession}
    end
  end

  def new
    @profession = Profession.new
    respond_to do  |format|
      format.html
      format.json {render json: @profession}
    end
  end

  def edit

  end

  def create
    @profession = Profession.new(params[:profession])
    respond_to do |format|
      if @profession.save
        format.html {redirect_to @profession, notice: "Profession was successfully created."}
        format.json {render json: @profession, status: :created, location: @profession}
      else
        format.html { render action: "new" }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

  end

  def destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/professions_helper.rb
module ProfessionsHelper
end

app/views/employees/_form.html.erb
<% @employee.professions.build %>
<%= form_for(@employee) do |employee_form| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= employee_form.label :name %><br />
    <%= employee_form.text_field :name %>
  </div>
  <div class="field">
    <%= employee_form.label :cpf %><br />
    <%= employee_form.text_field :cpf %>
  </div>
  <div class="field">
    <%= employee_form.label :contact %><br />
    <%= employee_form.text_field :contact %>
  </div>

    <h2>Tags</h2>
      <%= render :partial => 'professions/form',
                 :locals => {:form => employee_form} %>

  <div class="actions">
    <%= employee_form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing Employees</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Cpf</th>
    <th>Contact</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.id %></td>
    <td><%= employee.name %></td>
    <td><%= employee.cpf %></td>
    <td><%= employee.contact %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Id:</b>
  <%= @employee.id %>
</p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Cpf:</b>
  <%= @employee.cpf %>
</p>

<p>
  <b>Contact:</b>
  <%= @employee.contact %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/home/index.html.erb
<h1>Hospital Rails App</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Employee", employees_path %>
<br>
<%= link_to "Profession", professions_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospital</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #EEEEEE;">

<%= yield %>

</body>
</html>

app/views/professions/_form.html.erb
<%= form_for(@profession) do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/professions/_profession.html.erb
<p>
  <b>Profession:</b>
  <%= @profession.name %>
</p>

app/views/professions/edit.html.erb
<h1>Editing Profession</h1>

<%= render 'form' %>

<%= link_to 'Show', @profession %> |
<%= link_to 'Back', professions_path %>

app/views/professions/index.html.erb
<h1>Listing Professions</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @professions.each do |profession| %>
  <tr>
    <td><%= profession.id %></td>
    <td><%= profession.name %></td>

    <td><%= link_to 'Show', profession %></td>
    <td><%= link_to 'Edit', edit_profession_path(profession) %></td>
    <td><%= link_to 'Destroy', profession, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profession', new_profession_path %>

app/views/professions/new.html.erb
<h1>New Profession</h1>

<%= render 'form' %>

<%= link_to 'Back', professions_path %>

app/views/professions/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Id:</b>
  <%= @profession.id %>
</p>

<p>
  <b>Name:</b>
  <%= @profession.name %>
</p>

<%= link_to 'Edit', edit_profession_path(@profession) %> |
<%= link_to 'Back', professions_path %>